apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: <WORKLOAD_CLUSTER_NAME>
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  configuration: |
      terraform {
        backend "s3" {
          bucket   = "<PROJECT_STATE_STORE_BUCKET>"
          key      = "registry/clusters/<WORKLOAD_CLUSTER_NAME>/infrastructure/provider-config/terraform.tfstate"
          region = "<PROJECT_REGION>"
          encrypt = true
        }
        required_providers {
          civo = {
            source  = "civo/civo"
            version = "= 1.1.0"
          }
          aws = {
            source = "hashicorp/aws"
            version = ">= 5.30.0, < 6.0.0"
          }
        }
      }
      provider "aws" {
        alias  = "PROJECT_REGION"
        region = "<PROJECT_REGION>"
        allowed_account_ids = ["<PROJECT_AWS_ACCOUNT_ID>"]
        assume_role_with_web_identity {
          session_name = "kubefirst-pro"
          role_arn = "<PROJECT_ASSUME_ROLE>"
          web_identity_token_file = "/var/run/secrets/eks.amazonaws.com/serviceaccount/token"
        }
      }
      provider "civo" {
        credentials_file = "civo.json"
        region = "<WORKLOAD_CLUSTER_REGION>"
      }
  credentials:
  - filename: civo.json
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: <CLOUD_ACCOUNT_NAME>-civo-creds
      key: config.json
  - filename: .git-credentials
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: git-credentials
      key: creds
